create table if not exists agentflow_secrets (
  id bigint generated by default as identity primary key,
  name text not null,
  value_encrypted text not null,
  masked_value text,
  updated_at text
);
